### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-3-evaluacion-intermedia-Aleha20#1]
Hola @Aleha20 !

Quieres terminar el ejercicio antes de que te lo corrija? Si es así hazlo y avísame cuando termines vale!!!

**Comment by Aleha20** [comment]
Hola!!! si de hecho ya lo tengo hecho con fallos pero bueno mas de css ..
lo puedo meter en la master? lo tengo en una rama

Gracias !!!

**Comment by migueldelmazo** [comment]
Buen trabajo @Aleha20 !

### Algunas pistas para acabarlo:

- [ ] Mete todos tus estilos en la carpeta `stylesheets/`.
- [ ] Usa el estado de App.js para guardar los datos.
- [ ] Elimina los constructores vacíos que no solo tienen dentro el `super(...)` ya que no aportan nada.
- [ ] Pinta los tipos con un `ul` y varios `li`
- [ ] Elimina el código comentado, debuggers y consoles
- [ ] Usa propTypes para comprobar el tipo de dato de las props

### Cuando tengas esto si quieres puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón!!!
